#!/usr/bin/bash
# Attemp to Terminate and Remove previous session
if [ ! -d .git ]; then
    git clone https://github.com/hydra-13/forcesub -b master tmp_git
    mv tmp_git/.git .
    rm -rf tmp_git
fi

# start
python3 main.py
